development: &dev
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  telegram:
    bot:
      token: <%= ENV["TELEGRAM_BOT_TOKEN"] %>
      username: <%= ENV["TELEGRAM_BOT_USERNAME"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  telegram:
    bot:
      token: <%= ENV["TELEGRAM_BOT_TOKEN"] %>
      username: <%= ENV["TELEGRAM_BOT_USERNAME"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  telegram:
    bot:
      token: <%= ENV["TELEGRAM_BOT_TOKEN"] %>
      username: <%= ENV["TELEGRAM_BOT_USERNAME"] %>
